# Generated by Django 5.0.3 on 2025-04-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_task_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
    ]
